---
- id: shellcheck
  name: ShellCheck
  description: Static analysis tool for shell scripts
  language: haskell
  entry: shellcheck
  types: [shell]
  exclude_types: [zsh, fish, csh, tcsh]
  require_serial: false
  additional_dependencies:
    - ShellCheck-0.11.0
  minimum_pre_commit_version: '0'
- id: shellcheck-docker
  name: ShellCheck
  description: Static analysis tool for shell scripts
  language: docker_image
  entry: docker.io/koalaman/shellcheck:v0.11.0
  types: [shell]
  exclude_types: [zsh, fish, csh, tcsh]
- id: shellcheck-system
  name: ShellCheck
  description: Static analysis tool for shell scripts
  language: system
  entry: shellcheck
  types: [shell]
  exclude_types: [zsh, fish, csh, tcsh]
